apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway-service-server
  name: gateway-service-server
spec:
  ports:
    - name: "8080"
      port: 8080
  selector:
    app: gateway-service-server
status:
  loadBalancer: {}
