apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway-service-server
  name: gateway-service-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service-server
  strategy: {}
  template:
    metadata:
      labels:
        app: gateway-service-server
    spec:
      containers:
        - image: nrpndr/gateway-service:4.0
          name: gateway-service-server
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
