server:
  port: 8080
  servlet:
    context-path: /
    
spring:
  application:
    name: gateway-service
    
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service-server:9011
          predicates:
            - Path=/users,/users/{userId},/register,/login,/validateToken
            
        - id: movie-service
          uri: http://movie-service-server:80
          predicates:
            - Path=/fetch-all-movies,/fetch-movie-by-id/{id}
            
        - id: event-service
          uri: http://event-service-server:8095
          predicates:
            - Path=/events,/events/{eventId}

        - id: review-service
          uri: http://review-service-server:9014
          predicates:
            - Path=/movies/{movieId}/reviews,/movies/{movieId}/reviews/{reviewId},/events/{eventId}/reviews,/events/{eventId}/reviews/{reviewId}
    